//! Adversarial tile-seam robustness sweep for the native unwrapper.
//!
//! Loads every scene under `oracle/fixtures/seam/` (generated by
//! `oracle/gen_seam_sweep.py`) and, for each, compares the tiled native solve at
//! tile counts 2..=8 (odd AND even) against the GLOBAL native solve — which is
//! SNAPHU-parity at 0.011% per the residue-dense gate, so it is the oracle for
//! *tiling* robustness in isolation. Parity is measured PER CONNECTED COMPONENT
//! (each component carries an independent integer-cycle offset), exactly as
//! `native_dense_parity.rs` measures it against SNAPHU.
//!
//! Prints a table of per-component disagreement (%) for every (scene, tiles)
//! cell and flags any cell above the 0.5% gate. This is the measurement harness
//! behind PUSH-1 (kill the seam gap); run it before and after the stitch change.
//!
//! Run:  cargo run --release --example seam_sweep -p dolphin-unwrap

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use dolphin_core::Cf32;
use dolphin_unwrap::native::{unwrap_native, NativeConfig};
use ndarray::Array2;

const TWO_PI: f64 = std::f64::consts::TAU;
const GATE: f64 = 0.005;
const TILE_COUNTS: [usize; 7] = [2, 3, 4, 5, 6, 7, 8];

fn seam_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../oracle/fixtures/seam")
}

/// Most common integer offset in a slice of per-pixel cycle counts.
fn mode(cycles: &[i64]) -> i64 {
    let mut counts: HashMap<i64, usize> = HashMap::new();
    for &k in cycles {
        *counts.entry(k).or_insert(0) += 1;
    }
    counts
        .into_iter()
        .max_by_key(|&(_, c)| c)
        .map_or(0, |(k, _)| k)
}

/// Per-component cycle disagreement of `cand` vs `oracle`, grouped by `cc>0`.
fn disagreement(cand: &Array2<f32>, oracle: &Array2<f32>, cc: &Array2<u32>) -> f64 {
    let mut by_comp: HashMap<u32, Vec<i64>> = HashMap::new();
    for ((&label, &c), &o) in cc.iter().zip(cand.iter()).zip(oracle.iter()) {
        if label == 0 {
            continue;
        }
        by_comp
            .entry(label)
            .or_default()
            .push(((c as f64 - o as f64) / TWO_PI).round() as i64);
    }
    let (mut valid, mut bad) = (0usize, 0usize);
    for ks in by_comp.values() {
        let off = mode(ks);
        valid += ks.len();
        bad += ks.iter().filter(|&&k| k != off).count();
    }
    bad as f64 / valid.max(1) as f64
}

fn scene_tags(dir: &Path) -> Vec<String> {
    let mut tags: Vec<String> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("no seam fixtures at {dir:?}: {e} — run gen_seam_sweep.py"))
        .filter_map(|e| e.ok())
        .filter_map(|e| e.file_name().into_string().ok())
        .filter_map(|n| n.strip_suffix("_ifg.npy").map(str::to_owned))
        .collect();
    tags.sort();
    tags
}

fn main() {
    let dir = seam_dir();
    let tags = scene_tags(&dir);
    println!(
        "{:28} {:>6} {:>5} | {}",
        "scene",
        "comps",
        "—",
        TILE_COUNTS.map(|t| format!("{t}x{t}")).join("    ")
    );
    let mut worst = 0.0f64;
    let (mut worst_cell, mut fails) = (String::new(), 0usize);
    for tag in &tags {
        let ifg: Array2<Cf32> = ndarray_npy::read_npy(dir.join(format!("{tag}_ifg.npy"))).unwrap();
        let corr: Array2<f32> = ndarray_npy::read_npy(dir.join(format!("{tag}_corr.npy"))).unwrap();
        let global = unwrap_native(ifg.view(), corr.view(), &NativeConfig::default()).unwrap();
        let ncomp = global.conncomp.iter().copied().max().unwrap_or(0);
        let mut cells = String::new();
        for t in TILE_COUNTS {
            let cfg = NativeConfig {
                tile: Some((t, t)),
                ..NativeConfig::default()
            };
            let tiled = unwrap_native(ifg.view(), corr.view(), &cfg).unwrap();
            let d = disagreement(&tiled.unwrapped, &global.unwrapped, &global.conncomp);
            let flag = if d > GATE { '*' } else { ' ' };
            cells.push_str(&format!("{:>6.3}{} ", d * 100.0, flag));
            if d > GATE {
                fails += 1;
            }
            if d > worst {
                worst = d;
                worst_cell = format!("{tag} {t}x{t}");
            }
        }
        println!("{tag:28} {ncomp:>6} {:>5} | {cells}", "");
    }
    println!(
        "\nworst = {:.3}% at [{worst_cell}]   cells over {:.1}% gate: {fails}",
        worst * 100.0,
        GATE * 100.0
    );
}
