//! Residue-DENSE native-vs-SNAPHU parity guard (the standing CI gate).
//!
//! The Tier-2 oracle suite was 4/5 residue-free; only `lowcoh` (95 residues)
//! touched the MCF solver — far below real Sentinel-1 density (1e4-1e6). This
//! contract gates the native clean-room unwrapper on a committed residue-DENSE
//! golden (`unwdense_ci`: 256x256, ~2.3k residues = 3.6% of px, SIX SNAPHU
//! connected components split by near-zero-correlation moats + a masked band).
//! Generated by `oracle/gen_unwrap_dense.py` (realistic-synthetic: no real CSLC
//! burst was available; the coherence/noise statistics mirror a decorrelated
//! burst). SNAPHU produced the golden; this test never invokes it.
//!
//! Parity is measured PER CONNECTED COMPONENT: SNAPHU assigns an independent
//! integer-cycle offset to each component, so a single global mode is wrong on a
//! multi-component scene. For each SNAPHU component we take native's modal offset
//! and count pixels that disagree, then aggregate over all `conncomp > 0` pixels.
//!
//! Unlike `native_unwrap_contract.rs`, this FAILS (not skips) when the golden is
//! absent: the golden is committed, so a fresh checkout must guard parity.
//!
//! NOTE (documented boundary, not asserted): the native backend returns a
//! trivial single-component conncomp — it does not reproduce SNAPHU's coherence
//! masking / segmentation. The production `UnwrapBackend` trait discards conncomp
//! (returns only unwrapped phase), so this does not affect displacement output,
//! but it is why the default stays `SnaphuBackend`. See PLAYBOOK §Tier-2.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use dolphin_core::Cf32;
use dolphin_unwrap::native::{unwrap_native, NativeConfig};
use ndarray::Array2;

const TWO_PI: f64 = std::f64::consts::TAU;
/// Max fraction of `conncomp > 0` pixels allowed to disagree, per component.
const MAX_CYCLE_DISAGREE: f64 = 0.005;
/// Max sub-cycle (fractional) residual in radians on agreeing pixels.
const MAX_FRAC_RESIDUAL: f64 = 0.20;
const TAG: &str = "unwdense_ci";

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../oracle/fixtures")
}

fn load<T>(name: &str) -> Array2<T>
where
    T: ndarray_npy::ReadableElement,
{
    let path = fixtures().join(format!("{TAG}_{name}.npy"));
    ndarray_npy::read_npy(&path).unwrap_or_else(|e| {
        panic!(
            "missing committed residue-dense golden {path:?}: {e}\n\
             regenerate with `oracle/.venv/bin/python oracle/gen_unwrap_dense.py` \
             (DENSE_ROWS=256 DENSE_COLS=256 DENSE_LOOKS=4 DENSE_TAG=unwdense_ci)"
        )
    })
}

/// Most common integer offset within a slice of per-pixel cycle counts.
fn mode(cycles: &[i64]) -> i64 {
    let mut counts: HashMap<i64, usize> = HashMap::new();
    for &k in cycles {
        *counts.entry(k).or_insert(0) += 1;
    }
    counts
        .into_iter()
        .max_by_key(|&(_, c)| c)
        .map_or(0, |(k, _)| k)
}

#[test]
fn native_matches_snaphu_per_component_at_real_residue_density() {
    let ifg: Array2<Cf32> = load("ifg");
    let corr: Array2<f32> = load("corr");
    let oracle: Array2<f32> = load("oracle");
    let cc: Array2<u32> = load("conncomp");

    let out = unwrap_native(ifg.view(), corr.view(), &NativeConfig::default())
        .expect("native unwrap of residue-dense golden");

    // Per-pixel native-minus-oracle in integer cycles, grouped by SNAPHU comp.
    let mut by_comp: HashMap<u32, Vec<i64>> = HashMap::new();
    for ((&label, &n), &o) in cc.iter().zip(out.unwrapped.iter()).zip(oracle.iter()) {
        if label == 0 {
            continue;
        }
        let k = ((n as f64 - o as f64) / TWO_PI).round() as i64;
        by_comp.entry(label).or_default().push(k);
    }
    assert!(
        by_comp.len() >= 2,
        "golden must be multi-component (got {})",
        by_comp.len()
    );

    let offsets: HashMap<u32, i64> = by_comp.iter().map(|(&c, ks)| (c, mode(ks))).collect();
    let (mut valid, mut disagree) = (0usize, 0usize);
    for (label, ks) in &by_comp {
        valid += ks.len();
        disagree += ks.iter().filter(|&&k| k != offsets[label]).count();
    }
    let disagree_frac = disagree as f64 / valid.max(1) as f64;

    // Sub-cycle residual on pixels that agree in integer cycles.
    let max_frac = cc
        .iter()
        .zip(out.unwrapped.iter())
        .zip(oracle.iter())
        .filter(|((&l, _), _)| l > 0)
        .map(|((&l, &n), &o)| {
            let d = n as f64 - o as f64 - offsets[&l] as f64 * TWO_PI;
            (d - TWO_PI * (d / TWO_PI).round()).abs()
        })
        .fold(0.0, f64::max);

    eprintln!(
        "[{TAG}] components={} valid={valid} per-component-disagree={:.4}% frac-resid={max_frac:.4} rad",
        by_comp.len(),
        disagree_frac * 100.0,
    );
    assert!(
        disagree_frac <= MAX_CYCLE_DISAGREE,
        "native missed SNAPHU per-component cycle parity: {:.4}% > {:.2}%",
        disagree_frac * 100.0,
        MAX_CYCLE_DISAGREE * 100.0,
    );
    assert!(
        max_frac <= MAX_FRAC_RESIDUAL,
        "sub-cycle residual {max_frac:.4} rad > {MAX_FRAC_RESIDUAL} rad",
    );
}
